/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	ifcev1 "github.com/05sec/kubeifce/api/ifce/v1"
	versioned "github.com/05sec/kubeifce/pkg/clientset/versioned"
	internalinterfaces "github.com/05sec/kubeifce/pkg/informers/externalversions/internalinterfaces"
	v1 "github.com/05sec/kubeifce/pkg/listers/ifce/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BridgeInformer provides access to a shared informer and lister for
// Bridges.
type BridgeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.BridgeLister
}

type bridgeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBridgeInformer constructs a new informer for Bridge type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBridgeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBridgeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBridgeInformer constructs a new informer for Bridge type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBridgeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IfceV1().Bridges(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IfceV1().Bridges(namespace).Watch(context.TODO(), options)
			},
		},
		&ifcev1.Bridge{},
		resyncPeriod,
		indexers,
	)
}

func (f *bridgeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBridgeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *bridgeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ifcev1.Bridge{}, f.defaultInformer)
}

func (f *bridgeInformer) Lister() v1.BridgeLister {
	return v1.NewBridgeLister(f.Informer().GetIndexer())
}
