/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	ifcev1 "github.com/05sec/kubeifce/api/ifce/v1"
	versioned "github.com/05sec/kubeifce/pkg/clientset/versioned"
	internalinterfaces "github.com/05sec/kubeifce/pkg/informers/externalversions/internalinterfaces"
	v1 "github.com/05sec/kubeifce/pkg/listers/ifce/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VxlanInformer provides access to a shared informer and lister for
// Vxlans.
type VxlanInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.VxlanLister
}

type vxlanInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVxlanInformer constructs a new informer for Vxlan type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVxlanInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVxlanInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVxlanInformer constructs a new informer for Vxlan type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVxlanInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IfceV1().Vxlans(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IfceV1().Vxlans(namespace).Watch(context.TODO(), options)
			},
		},
		&ifcev1.Vxlan{},
		resyncPeriod,
		indexers,
	)
}

func (f *vxlanInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVxlanInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *vxlanInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ifcev1.Vxlan{}, f.defaultInformer)
}

func (f *vxlanInformer) Lister() v1.VxlanLister {
	return v1.NewVxlanLister(f.Informer().GetIndexer())
}
