/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/05sec/kubeifce/api/ifce/v1"
	ifcev1 "github.com/05sec/kubeifce/pkg/applyconfiguration/ifce/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVxlans implements VxlanInterface
type FakeVxlans struct {
	Fake *FakeIfceV1
	ns   string
}

var vxlansResource = v1.SchemeGroupVersion.WithResource("vxlans")

var vxlansKind = v1.SchemeGroupVersion.WithKind("Vxlan")

// Get takes name of the vxlan, and returns the corresponding vxlan object, and an error if there is any.
func (c *FakeVxlans) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Vxlan, err error) {
	emptyResult := &v1.Vxlan{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(vxlansResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Vxlan), err
}

// List takes label and field selectors, and returns the list of Vxlans that match those selectors.
func (c *FakeVxlans) List(ctx context.Context, opts metav1.ListOptions) (result *v1.VxlanList, err error) {
	emptyResult := &v1.VxlanList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(vxlansResource, vxlansKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.VxlanList{ListMeta: obj.(*v1.VxlanList).ListMeta}
	for _, item := range obj.(*v1.VxlanList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vxlans.
func (c *FakeVxlans) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(vxlansResource, c.ns, opts))

}

// Create takes the representation of a vxlan and creates it.  Returns the server's representation of the vxlan, and an error, if there is any.
func (c *FakeVxlans) Create(ctx context.Context, vxlan *v1.Vxlan, opts metav1.CreateOptions) (result *v1.Vxlan, err error) {
	emptyResult := &v1.Vxlan{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(vxlansResource, c.ns, vxlan, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Vxlan), err
}

// Update takes the representation of a vxlan and updates it. Returns the server's representation of the vxlan, and an error, if there is any.
func (c *FakeVxlans) Update(ctx context.Context, vxlan *v1.Vxlan, opts metav1.UpdateOptions) (result *v1.Vxlan, err error) {
	emptyResult := &v1.Vxlan{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(vxlansResource, c.ns, vxlan, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Vxlan), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVxlans) UpdateStatus(ctx context.Context, vxlan *v1.Vxlan, opts metav1.UpdateOptions) (result *v1.Vxlan, err error) {
	emptyResult := &v1.Vxlan{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(vxlansResource, "status", c.ns, vxlan, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Vxlan), err
}

// Delete takes name of the vxlan and deletes it. Returns an error if one occurs.
func (c *FakeVxlans) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(vxlansResource, c.ns, name, opts), &v1.Vxlan{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVxlans) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(vxlansResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.VxlanList{})
	return err
}

// Patch applies the patch and returns the patched vxlan.
func (c *FakeVxlans) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Vxlan, err error) {
	emptyResult := &v1.Vxlan{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(vxlansResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Vxlan), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied vxlan.
func (c *FakeVxlans) Apply(ctx context.Context, vxlan *ifcev1.VxlanApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Vxlan, err error) {
	if vxlan == nil {
		return nil, fmt.Errorf("vxlan provided to Apply must not be nil")
	}
	data, err := json.Marshal(vxlan)
	if err != nil {
		return nil, err
	}
	name := vxlan.Name
	if name == nil {
		return nil, fmt.Errorf("vxlan.Name must be provided to Apply")
	}
	emptyResult := &v1.Vxlan{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(vxlansResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Vxlan), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeVxlans) ApplyStatus(ctx context.Context, vxlan *ifcev1.VxlanApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Vxlan, err error) {
	if vxlan == nil {
		return nil, fmt.Errorf("vxlan provided to Apply must not be nil")
	}
	data, err := json.Marshal(vxlan)
	if err != nil {
		return nil, err
	}
	name := vxlan.Name
	if name == nil {
		return nil, fmt.Errorf("vxlan.Name must be provided to Apply")
	}
	emptyResult := &v1.Vxlan{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(vxlansResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions(), "status"), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Vxlan), err
}
