/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/05sec/kubeifce/api/ifce/v1"
	ifcev1 "github.com/05sec/kubeifce/pkg/applyconfiguration/ifce/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBridges implements BridgeInterface
type FakeBridges struct {
	Fake *FakeIfceV1
	ns   string
}

var bridgesResource = v1.SchemeGroupVersion.WithResource("bridges")

var bridgesKind = v1.SchemeGroupVersion.WithKind("Bridge")

// Get takes name of the bridge, and returns the corresponding bridge object, and an error if there is any.
func (c *FakeBridges) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Bridge, err error) {
	emptyResult := &v1.Bridge{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(bridgesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Bridge), err
}

// List takes label and field selectors, and returns the list of Bridges that match those selectors.
func (c *FakeBridges) List(ctx context.Context, opts metav1.ListOptions) (result *v1.BridgeList, err error) {
	emptyResult := &v1.BridgeList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(bridgesResource, bridgesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.BridgeList{ListMeta: obj.(*v1.BridgeList).ListMeta}
	for _, item := range obj.(*v1.BridgeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bridges.
func (c *FakeBridges) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(bridgesResource, c.ns, opts))

}

// Create takes the representation of a bridge and creates it.  Returns the server's representation of the bridge, and an error, if there is any.
func (c *FakeBridges) Create(ctx context.Context, bridge *v1.Bridge, opts metav1.CreateOptions) (result *v1.Bridge, err error) {
	emptyResult := &v1.Bridge{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(bridgesResource, c.ns, bridge, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Bridge), err
}

// Update takes the representation of a bridge and updates it. Returns the server's representation of the bridge, and an error, if there is any.
func (c *FakeBridges) Update(ctx context.Context, bridge *v1.Bridge, opts metav1.UpdateOptions) (result *v1.Bridge, err error) {
	emptyResult := &v1.Bridge{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(bridgesResource, c.ns, bridge, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Bridge), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBridges) UpdateStatus(ctx context.Context, bridge *v1.Bridge, opts metav1.UpdateOptions) (result *v1.Bridge, err error) {
	emptyResult := &v1.Bridge{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(bridgesResource, "status", c.ns, bridge, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Bridge), err
}

// Delete takes name of the bridge and deletes it. Returns an error if one occurs.
func (c *FakeBridges) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(bridgesResource, c.ns, name, opts), &v1.Bridge{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBridges) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(bridgesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.BridgeList{})
	return err
}

// Patch applies the patch and returns the patched bridge.
func (c *FakeBridges) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Bridge, err error) {
	emptyResult := &v1.Bridge{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(bridgesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Bridge), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied bridge.
func (c *FakeBridges) Apply(ctx context.Context, bridge *ifcev1.BridgeApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Bridge, err error) {
	if bridge == nil {
		return nil, fmt.Errorf("bridge provided to Apply must not be nil")
	}
	data, err := json.Marshal(bridge)
	if err != nil {
		return nil, err
	}
	name := bridge.Name
	if name == nil {
		return nil, fmt.Errorf("bridge.Name must be provided to Apply")
	}
	emptyResult := &v1.Bridge{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(bridgesResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Bridge), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeBridges) ApplyStatus(ctx context.Context, bridge *ifcev1.BridgeApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Bridge, err error) {
	if bridge == nil {
		return nil, fmt.Errorf("bridge provided to Apply must not be nil")
	}
	data, err := json.Marshal(bridge)
	if err != nil {
		return nil, err
	}
	name := bridge.Name
	if name == nil {
		return nil, fmt.Errorf("bridge.Name must be provided to Apply")
	}
	emptyResult := &v1.Bridge{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(bridgesResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions(), "status"), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.Bridge), err
}
