---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - interface.kubeifce.lwsec.cn
  resources:
  - vlans
  - vxlans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - interface.kubeifce.lwsec.cn
  resources:
  - vlans/finalizers
  - vxlans/finalizers
  verbs:
  - update
- apiGroups:
  - interface.kubeifce.lwsec.cn
  resources:
  - vlans/status
  - vxlans/status
  verbs:
  - get
  - patch
  - update
