# permissions for end users to view vxlans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubeifce
    app.kubernetes.io/managed-by: kustomize
  name: vxlan-viewer-role
rules:
- apiGroups:
  - interface.kubeifce.lwsec.cn
  resources:
  - vxlans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - interface.kubeifce.lwsec.cn
  resources:
  - vxlans/status
  verbs:
  - get
