apiVersion: interface.kubeifce.lwsec.cn/v1
kind: Vlan
metadata:
  name: vlan-sample
  labels:
    app.kubernetes.io/name: kubeifce
    app.kubernetes.io/managed-by: kustomize
spec:
  nodeName: node-1  # 指定节点名称
  id: 100           # 可选，VLAN ID
  master: eth0      # 可选，父接口名称
  mtu: 1496         # 可选，MTU大小
