/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// VlanSpecApplyConfiguration represents a declarative configuration of the VlanSpec type for use
// with apply.
type VlanSpecApplyConfiguration struct {
	NodeName *string `json:"nodeName,omitempty"`
	ID       *int    `json:"id,omitempty"`
	Master   *string `json:"master,omitempty"`
	MTU      *int    `json:"mtu,omitempty"`
}

// VlanSpecApplyConfiguration constructs a declarative configuration of the VlanSpec type for use with
// apply.
func VlanSpec() *VlanSpecApplyConfiguration {
	return &VlanSpecApplyConfiguration{}
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *VlanSpecApplyConfiguration) WithNodeName(value string) *VlanSpecApplyConfiguration {
	b.NodeName = &value
	return b
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *VlanSpecApplyConfiguration) WithID(value int) *VlanSpecApplyConfiguration {
	b.ID = &value
	return b
}

// WithMaster sets the Master field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Master field is set to the value of the last call.
func (b *VlanSpecApplyConfiguration) WithMaster(value string) *VlanSpecApplyConfiguration {
	b.Master = &value
	return b
}

// WithMTU sets the MTU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MTU field is set to the value of the last call.
func (b *VlanSpecApplyConfiguration) WithMTU(value int) *VlanSpecApplyConfiguration {
	b.MTU = &value
	return b
}
