/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// VxlanSpecApplyConfiguration represents a declarative configuration of the VxlanSpec type for use
// with apply.
type VxlanSpecApplyConfiguration struct {
	VNI      *int    `json:"vni,omitempty"`
	Master   *string `json:"master,omitempty"`
	MTU      *int    `json:"mtu,omitempty"`
	GroupIP  *string `json:"groupIP,omitempty"`
	RemoteIP *string `json:"remoteIP,omitempty"`
	LocalIP  *string `json:"localIP,omitempty"`
	TTL      *int    `json:"ttl,omitempty"`
	Port     *int    `json:"port,omitempty"`
}

// VxlanSpecApplyConfiguration constructs a declarative configuration of the VxlanSpec type for use with
// apply.
func VxlanSpec() *VxlanSpecApplyConfiguration {
	return &VxlanSpecApplyConfiguration{}
}

// WithVNI sets the VNI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VNI field is set to the value of the last call.
func (b *VxlanSpecApplyConfiguration) WithVNI(value int) *VxlanSpecApplyConfiguration {
	b.VNI = &value
	return b
}

// WithMaster sets the Master field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Master field is set to the value of the last call.
func (b *VxlanSpecApplyConfiguration) WithMaster(value string) *VxlanSpecApplyConfiguration {
	b.Master = &value
	return b
}

// WithMTU sets the MTU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MTU field is set to the value of the last call.
func (b *VxlanSpecApplyConfiguration) WithMTU(value int) *VxlanSpecApplyConfiguration {
	b.MTU = &value
	return b
}

// WithGroupIP sets the GroupIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupIP field is set to the value of the last call.
func (b *VxlanSpecApplyConfiguration) WithGroupIP(value string) *VxlanSpecApplyConfiguration {
	b.GroupIP = &value
	return b
}

// WithRemoteIP sets the RemoteIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteIP field is set to the value of the last call.
func (b *VxlanSpecApplyConfiguration) WithRemoteIP(value string) *VxlanSpecApplyConfiguration {
	b.RemoteIP = &value
	return b
}

// WithLocalIP sets the LocalIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalIP field is set to the value of the last call.
func (b *VxlanSpecApplyConfiguration) WithLocalIP(value string) *VxlanSpecApplyConfiguration {
	b.LocalIP = &value
	return b
}

// WithTTL sets the TTL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTL field is set to the value of the last call.
func (b *VxlanSpecApplyConfiguration) WithTTL(value int) *VxlanSpecApplyConfiguration {
	b.TTL = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *VxlanSpecApplyConfiguration) WithPort(value int) *VxlanSpecApplyConfiguration {
	b.Port = &value
	return b
}
