/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/05sec/kubeifce/api/ifce/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// VxlanLister helps list Vxlans.
// All objects returned here must be treated as read-only.
type VxlanLister interface {
	// List lists all Vxlans in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.Vxlan, err error)
	// Vxlans returns an object that can list and get Vxlans.
	Vxlans(namespace string) VxlanNamespaceLister
	VxlanListerExpansion
}

// vxlanLister implements the VxlanLister interface.
type vxlanLister struct {
	listers.ResourceIndexer[*v1.Vxlan]
}

// NewVxlanLister returns a new VxlanLister.
func NewVxlanLister(indexer cache.Indexer) VxlanLister {
	return &vxlanLister{listers.New[*v1.Vxlan](indexer, v1.Resource("vxlan"))}
}

// Vxlans returns an object that can list and get Vxlans.
func (s *vxlanLister) Vxlans(namespace string) VxlanNamespaceLister {
	return vxlanNamespaceLister{listers.NewNamespaced[*v1.Vxlan](s.ResourceIndexer, namespace)}
}

// VxlanNamespaceLister helps list and get Vxlans.
// All objects returned here must be treated as read-only.
type VxlanNamespaceLister interface {
	// List lists all Vxlans in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.Vxlan, err error)
	// Get retrieves the Vxlan from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.Vxlan, error)
	VxlanNamespaceListerExpansion
}

// vxlanNamespaceLister implements the VxlanNamespaceLister
// interface.
type vxlanNamespaceLister struct {
	listers.ResourceIndexer[*v1.Vxlan]
}
