/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/05sec/kubeifce/api/ifce/v1"
	ifcev1 "github.com/05sec/kubeifce/pkg/applyconfiguration/ifce/v1"
	scheme "github.com/05sec/kubeifce/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VxlansGetter has a method to return a VxlanInterface.
// A group's client should implement this interface.
type VxlansGetter interface {
	Vxlans(namespace string) VxlanInterface
}

// VxlanInterface has methods to work with Vxlan resources.
type VxlanInterface interface {
	Create(ctx context.Context, vxlan *v1.Vxlan, opts metav1.CreateOptions) (*v1.Vxlan, error)
	Update(ctx context.Context, vxlan *v1.Vxlan, opts metav1.UpdateOptions) (*v1.Vxlan, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, vxlan *v1.Vxlan, opts metav1.UpdateOptions) (*v1.Vxlan, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Vxlan, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.VxlanList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Vxlan, err error)
	Apply(ctx context.Context, vxlan *ifcev1.VxlanApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Vxlan, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, vxlan *ifcev1.VxlanApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Vxlan, err error)
	VxlanExpansion
}

// vxlans implements VxlanInterface
type vxlans struct {
	*gentype.ClientWithListAndApply[*v1.Vxlan, *v1.VxlanList, *ifcev1.VxlanApplyConfiguration]
}

// newVxlans returns a Vxlans
func newVxlans(c *IfceV1Client, namespace string) *vxlans {
	return &vxlans{
		gentype.NewClientWithListAndApply[*v1.Vxlan, *v1.VxlanList, *ifcev1.VxlanApplyConfiguration](
			"vxlans",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.Vxlan { return &v1.Vxlan{} },
			func() *v1.VxlanList { return &v1.VxlanList{} }),
	}
}
